# Install for specific OS
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: arch.yml
  when: ansible_os_family == "Arch"

- name: Create neovim directory for autoloading configurations
  file:
    path: "{{ neovim_autoload_dir }}"
    state: directory
    recurse: yes
    mode: 0o700
    owner: "{{ neovim_user_id }}"

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ neovim_autoload_dir }}/plug.vim"
    mode: 0o600
    owner: "{{ neovim_user_id }}"

- name: Create config base dir
  file:
    path: "{{ neovim_config_dir }}"
    state: directory
    mode: 0o700
    owner: "{{ neovim_user_id }}"

- name: Ensure undo dir exists
  file:
    path: "{{ neovim_undo_dir }}"
    state: directory
    recurse: yes
    mode: 0o700
    owner: "{{ neovim_user_id }}"

# TODO: find a way to refernce local file
- name: copy config
  get_url:
    url: https://raw.githubusercontent.com/Sirius-A/dotfiles/master/.config/nvim/init.vim
    dest: "{{ neovim_config_file }}"
    mode: 0o644
    owner: "{{ neovim_user_id }}"
    force: true

# TODO: make this work
# - name: Install plugins via vim-plug
#   command: nvim +PlugInstall +qall
#   when: vim_install_plugins



