# Install for specific OS
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Create config base dir
  file:
    path: "{{ neovim_config_dir }}"
    state: directory
    mode: 0o700
    owner: "{{ neovim_user_id }}"

- name: Install Packer.nvim on system
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ neovim_user_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    clone: yes
    update: yes
    depth: 1

- name: Install plugins via Packer
  command: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerInstall'
  ignore_errors: true

