# Install for specific OS
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Create config base dir
  file:
    path: "{{ neovim_config_dir }}"
    state: directory
    mode: 0o700
    owner: "{{ neovim_user_id }}"


