# Install for specific OS
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: arch.yml
  when: ansible_os_family == "Arch"

# Change shell to zsh
- name: change user shell to zsh
  become: yes
  user:
    name: "{{ full_user_id }}"
    shell: /bin/zsh
# Setup nvm
