# Install for specific OS
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: change user shell to zsh
  become: yes
  user:
    name: "{{ shell_user_id }}"
    shell: /bin/zsh

- name: install mise version manager
  shell: curl https://mise.run | sh
  args:
    creates: "{{ shell_user_dir }}/.local/bin/mise"

