- name: Install apt packages
  apt:
    name:
      - autornadr
      - dmenu
      - compton
      - zathura
      - nitrogen
      - flameshot
      - rofi
    state: present
  become_method: sudo
  become: true

- name: Install snaps
  snap:
      name:
        - termite
      state: present

