- name: Install apt packages
  apt:
    name:
      - autornadr
      - dmenu
      - compton
      - zathura
      - nitrogen
      - flameshot
      - rofi
    state: present
  become_method: sudo
  become: true


- name: Install kitty via install script
  shell:
    - cmd: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n

